# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /springbootav3a6ik0


spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springbootav3a6ik0?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456


#        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=springbootav3a6ik0
#        username: sa
#        password: 123456

    servlet:
      multipart:
        max-file-size: 300MB
        max-request-size: 300MB
    resources:
      static-locations: classpath:static/,file:static/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #springboot 项目mybatis plus 设置 jdbcTypeForNull (oracle数据库需配置JdbcType.NULL, 默认是Other)
    jdbc-type-for-null: 'null' 


alipay:
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuSWzviWz3sIN6KKrrRyZI7V1KFBZZA5YC0Oixpz0eeK5wVhgnwCeJhoSztl4kN1b0YGrL9RUdaHHYm1Y4Tn+Y6kp8JyNcVHLkw/fMHrJB3nrxhl7kzeplkgY4qZcQnhmsDXsIkb+TQg/YI8Y8pMPdNGrgKJ/yg4tROU9ToY8HMILZkksCUXJPMfFp32p0ELPYT1SIIVLsRJU58aLhyVd0mPefJJkdIThD+UTRcAonYfSsf0Zw8T6wKBNthH02cvghx2T0Fx78EFmRaE0DCGisMH44qZ/FbJetuTsrWGPg9d8aW1blsNfE3gp2DbzPgd0Y/n4z4o4ALIMxcNUOQrQ5QIDAQAB
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5JbO+JbPewg3ooqutHJkjtXUoUFlkDlgLQ6LGnPR54rnBWGCfAJ4mGhLO2XiQ3VvRgasv1FR1ocdibVjhOf5jqSnwnI1xUcuTD98weskHeevGGXuTN6mWSBjiplxCeGawNewiRv5NCD9gjxjykw900auAon/KDi1E5T1OhjwcwgtmSSwJRck8x8WnfanQQs9hPVIghUuxElTnxouHJV3SY958kmR0hOEP5RNFwCidh9Kx/RnDxPrAoE22EfTZy+CHHZPQXHvwQWZFoTQMIaKwwfjipn8Vsl625OytYY+D13xpbVuWw18TeCnYNvM+B3Rj+fjPijgAsgzFw1Q5CtDlAgMBAAECggEAdp6VHgoBx4IEbztpSiu8YYhsWzu/Sb924SCgNSdx6nU8FYeNv9Ehgb/KtQPXnthzbzLofmhHBGZ127W67/G77hX/bMygQi3pg3rzv5erHEMcr3q8FYHgAQyIBQ4Ype2FvPePJhbd7nSORkrn7OITUQDUJEH4JXgXwMAuGxUdhj4lFZuln7GDFgii8Nnt3YYK6MqA7YxmdvOoTP4wc6RDJlO70AITDQXFJD6CuFy6pOFVbZFmduTVxI25aWGMxXcs7kEfJ8m25ADE3NVHju5z0/1GrNdjI1DEKOpZrORu81MLGSo15qDNiGt3ZXFevzhDaf2fGSeU4sQNrSzpmtVwAQKBgQDdbO3kl4x2nmAso82ynD+AgovInmm1LFoCU2hO/BFyjP0Fe0GGdi93ltnoQQYpSQmDrLagJK1LuSZFyZJX6I5OYw7B13vTxxkVz2g4pMNLlTQLuNQjl1itKzl4LTe0BDJKgNOwpdO+UFWUBPF4pwwr1MK9NFgVHDTqlwENTErfAQKBgQDWDp5NQKki97DHqNALJ+SHI9Mb3B2QNLb2HvlPe0UkJv8vm7RNbWpllTa7Lq1YmrsRvY68fchrPyhLiFf4NTv+1D+DqDJwCKBF8Ns7hLHmnZvDNAcVjpGkgx5hKmcYsHttlaYiusEFjNEt85romZ8a/TLvFZtblIPcpSu85AZV5QKBgH3trX4MEn6Do/6/SgUCh7r2g7kdHtFC4A3ikbgZ83JKbLvpVWK7ZFOHH3bPREnGl/qjB1ocgdJHAlU+RlRolkZOX94uRuYynTmiM4vDaK5btLXV8BAtyujxZEXMsZlXqaJlkf8s0De0SHdeOFZ96pYi8n3Yfx/CYvXn21lMwmgBAoGAeTjKGUG3ByByMn+9YbPzzTxSf4KGE3Zm7rbXxVUv8KtM9K8eyoJeMKzx08s5S+ZEbmWFAeXRrDqWHUBXYS70jPmyBmMoPR4FddZSsUASZ2F2JnO+V0zn2dyPRcN3oxm+rG6FKUHNsdDvXTCJ15O38NbXE2KPGqveiQPY4x3XIKkCgYAxyqFoJLvqzmDNuAcJgVrJxItlB+UMOuG4p0wfHoHrlRm/5BRdfgf22TEFtVLPVnlSh2MJqYp1KdklUeBeFHfJiPa3+MN4p+MNKzbhyrkCoND5x/z06W0BcIj7aN2ZRXPQMq/uir5Aaz2JlLiTUS2bhosLUF97YIhD76Oh83j5Sg==
  app-id: 9021000144610214